[package]
name = "create_hw_folder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
formatx = "0.2.2"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.16"
